In [37]:
import cv2
import numpy as np

In [38]:
# import image
img = cv2.imread("card.png")
cv2.imshow("original", img)

cv2.waitKey(0)
cv2.destroyAllWindows()

width = 400
height = 500

In [39]:
pts1 = np.float32([[203,1],[1,472],[540,150],[338,617]])  #çevirmek istediğimiz resmin köşeleri
pts2 = np.float32([[0,0],[0,height],[width,0],[width,height]])
# pts1 in n. elemanı pts2 nin n. elemanıyla eşleştirilmeli

matrix = cv2.getPerspectiveTransform(pts1,pts2) #1 den 2 ye geçmek için gerkli transform matrixi oluşturulacak
print(matrix)

# final image
img_final = cv2.warpPerspective(img, matrix, (width, height))
cv2.imshow("final_image", img_final)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[ 9.87676881e-01  4.23589660e-01 -2.00921997e+02]
 [-3.91687206e-01  8.85896566e-01  7.86266062e+01]
 [-1.44400225e-05 -1.53164479e-05  1.00000000e+00]]
